Repository espeto-hub/uvlhub, pull requests merged in 2024-12, with the labels that each got.

#39 Delete unused test
  app/modules/hubfile/tests/test_unit.py
Labels: incidencia, baja

#44 test: improve test download all dataset
  app/modules/dataset/tests/locustfile.py
  app/modules/dataset/tests/test_selenium.py
  app/modules/dataset/tests/test_unit.py
Labels: incidencia, media

#58 Unificar formatting y linting
  .github/workflows/lint.yml
  .github/workflows/pre-commit.yml
  .pre-commit-config.yaml
  requirements.txt
Labels: incidencia, ci, alta

#67 Publicar imágen al crear release
  .github/workflows/image.yml
Labels: incidencia, cd, alta

#55 Bot integration
  .github/workflows/codacy_coverage.yml
  .github/workflows/tests.yml
  .gitignore
  app/__init__.py
  app/modules/auth/models.py
  app/modules/bot/__init__.py
  app/modules/bot/assets/scripts.js
  app/modules/bot/forms.py
  app/modules/bot/models.py
  app/modules/bot/repositories.py
  app/modules/bot/routes.py
  app/modules/bot/seeders.py
  app/modules/bot/services.py
  app/modules/bot/templates/bot/create_edit.html
  app/modules/bot/templates/bot/index.html
  app/modules/bot/tests/__init__.py
  app/modules/bot/tests/locustfile.py
  app/modules/bot/tests/test_selenium.py
  app/modules/bot/tests/test_unit.py
  app/modules/conftest.py
  app/modules/dataset/routes.py
  app/modules/flamapy/routes.py
  app/modules/hubfile/routes.py
  app/modules/profile/repositories.py
  app/modules/profile/services.py
  app/static/img/icons/icon-128x128.png
  app/static/img/icons/icon-256x256.png
  app/static/img/icons/icon-32x32.png
  app/static/img/icons/icon-72x72.png
  app/templates/base_template.html
  core/apprise/__init__.py
  core/apprise/apprise.py
  core/faker/__init__.py
  core/faker/faker.py
  migrations/versions/094bc564c1de_create_bot_model.py
  migrations/versions/144829fab01f_added_bot_service_name.py
  migrations/versions/3f3a8104c92c_bot_on_download_file.py
  migrations/versions/70fcac4d95ee_bot_unique_name_constraint.py
  migrations/versions/f0cd18e12ccc_added_bot_service_url.py
  requirements.txt
Labels: WI

#68 Rate datasets
  app/modules/auth/models.py
  app/modules/bot/tests/locustfile.py
  app/modules/dataset/forms.py
  app/modules/dataset/models.py
  app/modules/dataset/routes.py
  app/modules/dataset/services.py
  app/modules/dataset/templates/dataset/view_dataset.html
  app/modules/dataset/tests/locustfile.py
  app/modules/dataset/tests/test_selenium.py
  app/modules/dataset/tests/test_unit.py
  app/templates/base_template.html
  migrations/versions/094bc564c1de_create_bot_model.py
  migrations/versions/144829fab01f_added_bot_service_name.py
  migrations/versions/3f3a8104c92c_bot_on_download_file.py
  migrations/versions/70fcac4d95ee_bot_unique_name_constraint.py
  migrations/versions/dc5d8575a85e_create_dataset_ratings_table.py
  migrations/versions/f0cd18e12ccc_added_bot_service_url.py
  migrations/versions/fe893c367baa_agregando_columnas_user_id_y_created_at_.py
Labels: WI, media

#51 Advanced filtering
  app/modules/dataset/models.py
  app/modules/explore/assets/scripts.js
  app/modules/explore/templates/explore/index.html
  app/modules/explore/tests/test_selenium.py
Labels: WI

#74 incidencia: Fakenodo problems solved
  app/modules/dataset/forms.py
  app/modules/dataset/models.py
  app/modules/dataset/routes.py
  app/modules/dataset/templates/dataset/upload_dataset.html
Labels: incidencia, alta

#69 Despliegue en Vagrant
  vagrant/04_install_dependencies.yml
Labels: incidencia, media

#75 Mejor Docker Compose en producción
  docker/docker-compose.prod.ssl.yml
  docker/docker-compose.prod.tailscale.yml
  docker/docker-compose.prod.yml
  docker/images/Dockerfile.prod
  docker/tailscale/config.json
Labels: incidencia, alta

#77 Borrar documentación desactualizada
  docs/Acta-fundacional-espeto.md
  docs/diario.md
Labels: incidencia, baja
